# Generated by Django 6.1.1 on 2026-09-19 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_asset_classes',
                'ordering': ('-amount',),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('group', models.CharField(choices=[('morning', 'Manhã'), ('focus', 'Foco & Estudo'), ('body', 'Corpo & Saúde'), ('night', 'Noturno')], default='focus', max_length=10)),
                ('goal', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(default='book-open-variant', max_length=40)),
                ('streak', models.PositiveIntegerField(default=0, help_text='Sequência atual em dias.')),
                ('scheduled_at', models.TimeField(blank=True, null=True)),
                ('quantity_current', models.PositiveIntegerField(default=0)),
                ('quantity_target', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_step', models.PositiveIntegerField(default=1)),
                ('quantity_unit', models.CharField(blank=True, max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_hours', models.PositiveSmallIntegerField(default=25)),
                ('workouts', models.PositiveSmallIntegerField(default=5)),
                ('habits_consistency', models.PositiveSmallIntegerField(default=85, help_text='Consistência mínima, em %.')),
                ('monthly_savings', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('quotes_enabled', models.BooleanField(default=True)),
                ('quote_curators', models.JSONField(default=list, help_text='Curadorias ativas (Profile.Curator).')),
                ('quote_time', models.TimeField(default='07:00')),
                ('wake_time', models.TimeField(default='06:00')),
                ('bed_time', models.TimeField(default='22:30')),
                ('wind_down_minutes', models.PositiveSmallIntegerField(default=30, help_text='0 = desligado.')),
                ('blue_light_filter', models.BooleanField(default=True)),
                ('dim_at_dusk', models.BooleanField(default=True)),
                ('habit_reminders', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('status', models.CharField(choices=[('done', 'Concluído'), ('next', 'Próximo'), ('pending', 'Pendente')], default='pending', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_schedule_blocks',
                'ordering': ('date', 'start'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('module', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('normal', 'Em andamento'), ('high', 'Alta prioridade'), ('review', 'Revisão hoje')], default='normal', max_length=10)),
                ('hours_done', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hours_goal', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_subjects',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('due', models.BooleanField(default=True, help_text='Pendente de revisão.')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='brain.subject')),
            ],
            options={
                'db_table': 'study_flashcards',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('income', 'Receita'), ('essential', 'Despesa Essencial'), ('investment', 'Investimento'), ('lifestyle', 'Estilo de Vida')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Sempre positivo; `kind` define o sinal.', max_digits=12)),
                ('date', models.DateField()),
                ('icon', models.CharField(default='cash-multiple', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_transactions',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('time', models.TimeField(blank=True, help_text='Horário previsto.', null=True)),
                ('intensity', models.CharField(choices=[('low', 'Leve'), ('moderate', 'Moderada'), ('high', 'Alta intensidade')], default='moderate', max_length=10)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('volume_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='brain.workout')),
            ],
            options={
                'db_table': 'training_logs',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(blank=True, help_text="Texto livre: '8-10 reps', '60 seg'.", max_length=60)),
                ('load', models.DecimalField(decimal_places=2, default=0, help_text='kg; 0 = peso corporal/cardio.', max_digits=6)),
                ('delta', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('muscle', models.CharField(blank=True, max_length=80)),
                ('group', models.CharField(choices=[('abc', 'Divisão ABC'), ('cardio', 'Cardio & Mobilidade')], default='abc', max_length=10)),
                ('icon', models.CharField(default='dumbbell', max_length=40)),
                ('done', models.BooleanField(default=False)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='brain.workout')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='brain.habit')),
            ],
            options={
                'db_table': 'habit_logs',
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='uniq_habit_log_habit_date')],
            },
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_logs',
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_study_log_user_date')],
            },
        ),
    ]
