# Generated by Django 6.1.1 on 2026-09-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expense_ceiling',
            field=models.DecimalField(decimal_places=2, default=8500, help_text='Teto mensal de despesas.', max_digits=12),
        ),
    ]
